# Project information
site_name: "COVID-19 Test Registierung Software Documentation"
site_description: 'Documentation of the COVID-19 Test Registierung project Software'
site_author: 'Pawel Sikora'

# Navigation bar
nav:
        - Overview: 'README.md'
        - Project Management: 'project_management.md'
        - Resources:
                - Get Started: 'get_started.md'
                - Backend (API): 'backend.md'
                - Frontend (Client): 'frontend.md'
                - Hosting: 'hosting.md'
        - Links: 'links.md'

# Repo
repo_name: 'COVID-19 Test Registierung repo'
repo_url: 'https://github.com/schmiddim/0583-App-zur-Registrierung-Infizierter'
edit_uri: 'docs/edit/master/docs/'

extra:
  repo_icon: 'github'

markdown_extensions:
        - attr_list
        - codehilite
# Theme
theme:
       name: 'material'

palette:
       primary: 'deep orange'
       accent: 'blue'

# Plugins
plugins:
  - search
  - git-revision-date-localized

# Copyright
copyright: 'Copyright COVID-19 Test Registierung Team, 2020'
